spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apidemo?serverTimezone=UTC
    username: root
    password: vikkidchamp
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect